version: "3.9"

services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - myvolume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - my_network

  backend:
    build: ./Bingo-Driven-BackEnd
    image: backend
    container_name: backend_container
    env_file:
      - Bingo-Driven-BackEnd/.env
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "npx prisma migrate deploy && node dist/src/server.js"
    networks:
      - my_network

networks:
  my_network:

volumes:
  myvolume:
