services:
  postgres:
    image: postgres:17-alpine
    env_file:
      - .env.test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - mynetwork

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder          
    image: bingo-backend:test
    command: >
      sh -c "
        npx prisma migrate deploy &&
        npm run test:ci
      "
    env_file:
      - .env.test
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - mynetwork

networks:
  mynetwork: {}
